version: '3.8'

services:
  api:
    build:
      context: .
    image: express-template-api
    container_name: express-template-api
    restart: unless-stopped
    env_file: .env
    environment:
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=3000
    ports:
      - "3000:3000"
