version: '3.8'

services:
  api:
    build:
      context: .
    image: express-template-api
    container_name: express-template-api
    restart: unless-stopped
    env_file: .env
    environment:
      - SERVER_HOSTNAME=0.0.0.0
      - SERVER_PORT=3000
      - DATABASE_URI=mongodb://database:27017/api
    ports:
      - "3000:3000"
    depends_on:
      - database-setup

  database-setup:
    image: mongo:5.0.6
    container_name: express-template-database-setup
    restart: on-failure
    entrypoint:
      - /scripts/mongodb-replica-setup.sh
    volumes:
      - ./scripts:/scripts
    depends_on:
      - database

  database:
    image: mongo:5.0.6
    container_name: express-template-database
    restart: unless-stopped
    command: --bind_ip_all --replSet rs0
    environment:
      - MONGO_INITDB_DATABASE=api
    ports:
      - "27017:27017"
    volumes:
      - database-data:/data/db

volumes:
  database-data:
