name: Staging Deployment

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    uses: ./.github/workflows/deployment.yml

    with:
      environment: staging

    needs:
      - test
